name: API Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 1: Download allurectl utility
    - name: Download allurectl
      uses: allure-framework/setup-allurectl@v1

    # Step 2: Run allurectl job-run to create a test plan file
    - name: Create Allure TestOps test plan
      run: |
        allurectl job-run create \
          --endpoint ${{ secrets.ALLURE_ENDPOINT }} \
          --project-id ${{ secrets.ALLURE_PROJECT_ID }} \
          --token ${{ secrets.ALLURE_TOKEN }} \
          --name "Your Test Plan Name" \
          --results-directory "build/allure-results"

    # Step 3: Run tests and wrap with allurectl watch
    - name: Run API tests with Allure integration
      run: |
        allurectl watch --allure-results "build/allure-results" \
          pytest tests/ -k "not test_register_mock"
